### ISSUE TITLE
build reporter crashes with certain versions if wide

### ISSUE THREAD

**Issue by chrismatheson** [webdriverio/wdio-jasmine-framework#17]
Ive just had the following crash 

```
/Users/chrismatheson/Code/teachersregister/web/node_modules/webdriverio/build/lib/utils/BaseReporter.js:336
                        throw _iteratorError;
                        ^

TypeError: Cannot read property 'split' of undefined
    at /Users/chrismatheson/Code/teachersregister/web/node_modules/wdio-spec-reporter/build/reporter.js:267:43
    at Array.forEach (native)
    at SpecReporter.getFailureList (/Users/chrismatheson/Code/teachersregister/web/node_modules/wdio-spec-reporter/build/reporter.js:265:22)
    at SpecReporter.getSuiteResult (/Users/chrismatheson/Code/teachersregister/web/node_modules/wdio-spec-reporter/build/reporter.js:318:28)
    at SpecReporter.printSuiteResult (/Users/chrismatheson/Code/teachersregister/web/node_modules/wdio-spec-reporter/build/reporter.js:326:30)
    at SpecReporter.<anonymous> (/Users/chrismatheson/Code/teachersregister/web/node_modules/wdio-spec-reporter/build/reporter.js:109:18)
    at emitOne (events.js:77:13)
    at SpecReporter.emit (events.js:169:7)
    at BaseReporter.handleEvent (/Users/chrismatheson/Code/teachersregister/web/node_modules/webdriverio/build/lib/utils/BaseReporter.js:324:35)
    at Launcher.messageHandler (/Users/chrismatheson/Code/teachersregister/web/node_modules/webdriverio/build/lib/launcher.js:590:28)
```

i think this is from your latest change https://github.com/webdriverio/wdio-jasmine-framework/commit/64373dd397363757eeebcdad71555bf1841ef366

where if an error does not contain a stack it will error with an internal error rather than the original

maybe this is something to do with warnings vs errors?

**Comment by chrismatheson** [comment]
FYI for now i have just rolled back to previously working v0.2.3

**Comment by christian-bromann** [comment]
@chrismatheson can you provide a reproducible example?

**Comment by christian-bromann** [comment]
Closing due to inactivity.
