### ISSUE TITLE
Add option to suppress stack trace on test failure

### ISSUE THREAD

**Issue by nfriend** [webdriverio/wdio-jasmine-framework#22]
I'm not sure if this is the correct place to request this feature, but it would be great to be able suppress stack traces when tests fail, similar to the `--noStack` option provided by [jasmine-node](https://github.com/mhevery/jasmine-node).

**Comment by christian-bromann** [comment]
@nfriend can you give an example of a stack trace you want to suppress?

**Comment by nfriend** [comment]
Sure:

```bash
[chrome #0-1] Session ID: 8193fe56-85c3-4efc-9acb-e8aa844e3702
[chrome #0-1] Spec: C:\Users\nfriend\code\generator-angular-app-test\e2e-tests\example.spec.ts
[chrome #0-1] Running: chrome
[chrome #0-1]
[chrome #0-1]   Example UI Tests
[chrome #0-1]       1) ensures that the user was warmly greeted
[chrome #0-1]
[chrome #0-1]
[chrome #0-1] 1 failing (4s)
[chrome #0-1]
[chrome #0-1] 1) Example UI Tests ensures that the user was warmly greeted:
[chrome #0-1] Expected 'Welcome to Generator Angular App Test!' to match /^Something else.*!$/.
[chrome #0-1] Error: Expected 'Welcome to Generator Angular App Test!' to match /^Something else.*!$/.
[chrome #0-1]     at stack (C:\Users\nfriend\code\generator-angular-app-test\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1640:17)
[chrome #0-1]     at buildExpectationResult (C:\Users\nfriend\code\generator-angular-app-test\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1610:14)
[chrome #0-1]     at Spec.expectationResultFactory (C:\Users\nfriend\code\generator-angular-app-test\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:655:18)
[chrome #0-1]     at Spec.addExpectationResult (C:\Users\nfriend\code\generator-angular-app-test\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:342:34)
[chrome #0-1]     at Expectation.addExpectationResult (C:\Users\nfriend\code\generator-angular-app-test\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:599:21)
[chrome #0-1]     at Expectation.toMatch (C:\Users\nfriend\code\generator-angular-app-test\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1564:12)
[chrome #0-1]     at Object.<anonymous> (C:\Users\nfriend\code\generator-angular-app-test\e2e-tests\example.spec.ts:8:29)
[chrome #0-1]     at C:\Users\nfriend\code\generator-angular-app-test\node_modules\wdio-sync\build\index.js:756:26
[chrome #0-1]     at Object.executeSync (C:\Users\nfriend\code\generator-angular-app-test\node_modules\wdio-sync\build\index.js:754:12)
[chrome #0-1]     at C:\Users\nfriend\code\generator-angular-app-test\node_modules\wdio-sync\build\index.js:952:38
[chrome #0-1]

[10:06:21] 'e2e-test' errored after 5.57 s
[10:06:21] Error in plugin 'gulp-webdriver'
Message:
    wdio exited with code 1

C:\Users\nfriend\code\generator-angular-app-test>
```

Although now that I look closer at the issue, perhaps this is an option that needs to be implemented in [webdriverio/wdio-spec-reporter](https://github.com/webdriverio/wdio-spec-reporter)?

**Comment by christian-bromann** [comment]
I added stacktrace cleaning (which can be disabled by applying option `cleanStack: false`). Once you update to `v0.3.0` your stack will look like this:

```js
[chrome #0-1] Session ID: 8193fe56-85c3-4efc-9acb-e8aa844e3702
[chrome #0-1] Spec: C:\Users\nfriend\code\generator-angular-app-test\e2e-tests\example.spec.ts
[chrome #0-1] Running: chrome
[chrome #0-1]
[chrome #0-1]   Example UI Tests
[chrome #0-1]       1) ensures that the user was warmly greeted
[chrome #0-1]
[chrome #0-1]
[chrome #0-1] 1 failing (4s)
[chrome #0-1]
[chrome #0-1] 1) Example UI Tests ensures that the user was warmly greeted:
[chrome #0-1] Expected 'Welcome to Generator Angular App Test!' to match /^Something else.*!$/.
[chrome #0-1] Error: Expected 'Welcome to Generator Angular App Test!' to match /^Something else.*!$/.
[chrome #0-1]     at Object.<anonymous> (C:\Users\nfriend\code\generator-angular-app-test\e2e-tests\example.spec.ts:8:29)
[chrome #0-1]

[10:06:21] 'e2e-test' errored after 5.57 s
[10:06:21] Error in plugin 'gulp-webdriver'
Message:
    wdio exited with code 1

C:\Users\nfriend\code\generator-angular-app-test>
```
