### ISSUE TITLE
throws an erro

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/wdio-jasmine-framework#5]
see webdriverio/webdriverio#1073
```
Error: Cannot generate spec hash for runner with no 'specs' key
    at Error (native)
    at ReporterStats.getSpecHash (/Users/justin.williams/.nvm/versions/node/v5.0.0/lib/node_modules/webdriverio/build/lib/utils/ReporterStats.js:212:42)
    at ReporterStats.getSpecStats (/Users/justin.williams/.nvm/versions/node/v5.0.0/lib/node_modules/webdriverio/build/lib/utils/ReporterStats.js:227:33)
    at ReporterStats.suiteStart (/Users/justin.williams/.nvm/versions/node/v5.0.0/lib/node_modules/webdriverio/build/lib/utils/ReporterStats.js:239:18)
    at BaseReporter.<anonymous> (/Users/justin.williams/.nvm/versions/node/v5.0.0/lib/node_modules/webdriverio/build/lib/utils/BaseReporter.js:134:25)
    at emitOne (events.js:77:13)
    at BaseReporter.emit (events.js:169:7)
    at BaseReporter.handleEvent (/Users/justin.williams/.nvm/versions/node/v5.0.0/lib/node_modules/webdriverio/build/lib/utils/BaseReporter.js:326:27)
    at Launcher.messageHandler (/Users/justin.williams/.nvm/versions/node/v5.0.0/lib/node_modules/webdriverio/build/lib/launcher.js:469:28)
    at emitTwo (events.js:87:13)
```

**Comment by AndyOGo** [comment]
I get the same error since i switched to jasmine:(

**Comment by dgasi** [comment]
hi Guys,

I managed to get rid of the error with downgrading wdio from 4.0.3 to 3.4.0.

BR.

**Comment by christian-bromann** [comment]
This is fixed with the latest release
